_format_version: "3.0"

services:
  - name: juiceshop-service
    url: http://juiceshop-backend:3000
    routes:
      - name: juiceshop-route
        paths:
          - /

plugins:
- name: open-appsec-waf-kong-plugin
  route: juiceshop-route
  config: {}

